FROM alpine:latest
FROM node:22-alpine AS node
FROM php:8.1.31-cli-alpine AS php
FROM golang:1.23.4-alpine AS golang

# Dependecies lib
RUN apk add --no-cache gcompat libstdc++ build-base gcc g++ oniguruma-dev libxml2 libsodium-dev gnu-libiconv readline sqlite-libs curl argon2-libs
RUN apk add --no-cache --virtual=.build-deps build-base sqlite-dev \
  && apk del .build-deps


COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN node -v

COPY --from=php /usr/local/bin/php /usr/local/bin/php
COPY --from=php /usr/local/lib/php /usr/local/lib/php
COPY --from=php /usr/local/etc/php /usr/local/etc/php

RUN cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini && \
        sed -i -e "s/^ *display_errors.*/display_errors = on/g" /usr/local/etc/php/php.ini

RUN php --ini

RUN php -v

COPY --from=golang /usr/local/go /usr/local/go

RUN go version

WORKDIR /app

COPY ./bin/linux_amd64/app ./
COPY ./web/dist ./web/dist
COPY ./web/dist/vite.svg ./web/dist
COPY .env.prod .env.prod

EXPOSE 9001

CMD ["./app","-mode","prod"]
